In [6]:
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [7]:
from sklearn import preprocessing

In [8]:
df_global = pd.read_csv('trainmfcc.csv')

In [16]:
test = pd.read_csv('trainmfcc2.csv')

In [17]:
test.tail()

0           1          2          3          4         5  \
64716 -747.565986  121.224962  20.246739  32.797113  15.918801  1.286000   
64717 -722.127320  132.149577  14.330414  38.486279  14.604170 -3.059901   
64718 -734.285115  128.649448  15.660269  30.867015  16.518786  0.406024   
64719 -738.591396  124.548023  16.548505  35.370693  22.550344  7.591664   
64720 -645.907779  167.815133 -16.317952  30.916498  10.137046 -7.153182   

               6          7          8         9  ...        225       226  \
64716  17.509572   6.652919  -0.123550 -1.291902  ...  -2.403336 -1.394872   
64717  20.285662   4.461004  -1.204861  2.535550  ...  -2.198526 -3.453572   
64718  14.322426   4.105905   3.258389  3.330035  ...  -3.202651 -1.585738   
64719  18.998440   5.724688   4.741736  2.978369  ...  -2.481681 -2.712879   
64720  24.870192 -12.007109 -14.486046  1.509704  ...  -4.488733 -2.694302   

            227       228       229       230       231       232       233  \
64716 -4.425967 -2.857053 -0.832394 -1.225613 -1.080543 -1.227494 -0.895603   
64717 -2.961358 -1.361430 -1.815778 -3.007297 -2.709955 -1.127327 -1.222344   
64718 -5.159744 -1.528805 -1.360037 -1.258236 -1.430894 -1.680614 -1.688991   
64719 -4.179033 -1.044358 -1.793707 -1.608901 -1.394310 -0.983468 -2.100168   
64720 -2.316893 -1.937843 -1.970090 -2.299204 -1.668272 -1.574119 -1.222939   

       word  
64716    29  
64717    29  
64718    29  
64719    29  
64720    29  

[5 rows x 235 columns]

In [9]:
df_global.shape

(64721, 235)

In [10]:
le = preprocessing.LabelEncoder()
df_global['word'] = le.fit_transform(df_global['word'].astype(str))

In [11]:
lb = preprocessing.LabelBinarizer()
lb.fit(df_global['word'])

LabelBinarizer(neg_label=0, pos_label=1, sparse_output=False)

In [12]:
df_global

0           1           2          3          4          5  \
0     -785.672759   91.026006    0.250741  11.375646  23.574704   3.071190   
1     -653.656524  115.020857  -86.540856  35.350463  43.358153 -22.182289   
2     -597.560192  140.314379 -103.666156  40.326567  44.499551 -26.065558   
3     -675.642472  150.953403  -17.602592  26.343432  24.152475  -1.780365   
4     -683.174369  147.738534  -14.738978  26.039724  23.369979  -2.603799   
5     -611.603807  171.397235  -44.631937  36.546595  22.187225 -12.028502   
6     -620.412019  158.370747  -53.437136  36.176107  25.565544  -7.912161   
7     -832.597417   62.845572    9.768816   1.940403   4.269753   3.077615   
8     -762.080932  109.012839   -7.746951  -4.084803  16.552188  -0.042529   
9     -805.851518   76.543918    9.232182  12.779811   5.009305  -1.909063   
10    -592.142406  172.457484  -46.895889  59.823935  26.218368 -18.113066   
11    -657.525892  160.868918  -11.269921  47.076017  30.639507  -4.118544   
12    -693.544000  141.447891   -5.229655  39.290385  26.083646  -3.004579   
13    -733.278351  125.583913   -4.337479  17.237303  27.863391  -3.453292   
14    -571.674890  194.252696  -52.370912  34.046358  10.537621 -25.423077   
15    -585.951113  182.857587  -52.514110  32.976383   7.107373 -25.629394   
16    -754.494960   97.586019  -16.526206  29.272491  37.921029 -24.751633   
17    -643.635887  195.432628   -6.103092   6.773122  21.210071  -2.383970   
18    -641.025887  167.434839  -30.967225  28.830473  32.406375  -1.355853   
19    -741.922100  104.999725   -6.415191  29.668921   8.892696 -13.928326   
20    -719.572756  143.682163   -2.304757   9.737338  37.937022   9.475073   
21    -680.352192  160.653479   -4.987435  22.338950  27.378546   5.853790   
22    -664.531087  165.045989  -17.015145  16.786418  23.066533  -0.648820   
23    -685.218320  122.948614  -57.139119  -2.120008   6.197072 -17.971750   
24    -667.197113  136.012925  -59.638610  12.282997  32.527485 -18.177322   
25    -765.606612   89.293835  -12.781415  17.281687  11.454434  -9.286961   
26    -702.820760  159.107947    3.330872   0.765661   7.752856 -10.972386   
27    -819.068091   72.382045   15.992702  16.508774  12.839232  -3.182780   
28    -739.979532  102.030979  -12.896276  26.575218  10.397998  -9.075486   
29    -610.460338  166.853412  -46.017623  50.843491  36.143916  -5.068723   
...           ...         ...         ...        ...        ...        ...   
64691 -711.714306  142.697713    6.861018  22.784043  11.822719  -1.436612   
64692 -643.167126  170.977593  -20.987188  31.099404  28.217159   2.749851   
64693 -753.984891   84.249647  -27.253312  26.600264  23.966889  -0.539236   
64694 -774.437043   83.302525  -13.786518  17.850110  20.256476   2.614846   
64695 -559.419665  193.959201  -54.861267  47.584305  13.338882 -24.593789   
64696 -550.210562  168.348968  -82.708355  62.387427  17.450876 -20.698353   
64697 -579.235841  155.243912  -76.055276  60.549019  20.306477 -21.738697   
64698 -531.505478  175.067543  -91.947300  62.224453  15.993333 -23.942814   
64699 -555.480518  165.493745  -84.640136  59.511083  17.619857 -23.065382   
64700 -519.016394  179.520931  -95.290168  63.407227  15.013854 -24.958648   
64701 -574.538031  184.739836  -45.772777  54.325347  20.529757 -15.606124   
64702 -538.201655  214.122243  -50.657756  36.449749  15.832689 -14.979686   
64703 -726.580814  155.178992   21.348345  -0.356235  11.726303   5.916075   
64704 -642.971336  169.525779  -28.749036  18.126052  15.822062 -11.470806   
64705 -639.098023  145.596658  -56.872150  26.201978  17.129946 -12.692731   
64706 -614.584697  162.716285  -60.307048  22.699155  15.732121 -14.936460   
64707 -665.543356  135.791855  -37.269367  27.498590   1.513526  -9.980031   
64708 -637.633490  135.330606  -54.553011  44.056240   5.435703 -16.541726   
64709 -755.862156  123.009519    5.739233  -4.398401  10.126328  -0.366929   
64710 -734.291619  142.042433   27.345

In [13]:
df_global.to_csv('trainmfcc2.csv', index = False)

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>

Holdout - diviser le dataset en ensemble d'apprentissage et test

<br><br></p>



In [8]:
y=df_global[['word']].copy()

In [9]:
X=df_global.copy()
del X['word']

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=324)

#  ExtraTreesClassifier

In [11]:
from sklearn.ensemble import ExtraTreesClassifier
extra_trees =ExtraTreesClassifier()
extra_trees.fit(X_train, y_train)
prediction = extra_trees.predict(X_test)

C:\Users\hafsa\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
C:\Users\hafsa\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


In [13]:
acc=accuracy_score(y_true = y_test, y_pred = prediction)
precision=precision_score(y_test,prediction,average=None)
recall=recall_score(y_test,prediction,average=None)
mesure=f1_score(y_test,prediction,average=None)

In [14]:
print(acc)

0.45364734525704653


# AdaBoostClassifier

In [15]:
from sklearn.ensemble import AdaBoostClassifier
ada_reg = AdaBoostClassifier()
ada_reg.fit(X_train, y_train)

C:\Users\hafsa\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [17]:
prediction_ = ada_reg.predict(X_test)

In [18]:
acc_=accuracy_score(y_true = y_test, y_pred = prediction_)
precision_=precision_score(y_test,prediction_,average=None)
recall_=recall_score(y_test,prediction_,average=None)
mesure_=f1_score(y_test,prediction_,average=None)

In [19]:
print(acc_)

0.4050472890720105


<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>

apprendre le modèle  Decision Tree
<br><br></p>



In [20]:
d_tree=DecisionTreeClassifier(max_leaf_nodes=10, random_state=0)
d_tree.fit(X_train, y_train)
predictions1 = d_tree.predict(X_test)

In [21]:
predictions1[:10]

array([15, 15, 23, 21, 15, 15, 26, 15, 23, 17], dtype=int64)

In [22]:
y_test['word'][:10]

59636    27
60866    28
29665    14
46825    21
18072     7
34393    16
28850    14
27842    13
53186    24
25632    12
Name: word, dtype: int64

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>

KNN
<br><br></p>

In [23]:
from sklearn.neighbors import KNeighborsClassifier


In [24]:
neighbor =KNeighborsClassifier(n_neighbors=3)
neighbor.fit(X_train, y_train)

C:\Users\hafsa\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [25]:
predictions2 =neighbor.predict(X_test)
predictions2[:12]

array([27, 25, 13,  5,  7, 15, 14,  4, 24, 12,  6,  7], dtype=int64)

In [26]:
y_test['word'][:12]

59636    27
60866    28
29665    14
46825    21
18072     7
34393    16
28850    14
27842    13
53186    24
25632    12
47812    22
3311      1
Name: word, dtype: int64

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>

La modèle SVM (Kernelized Support Vector Machines)
<br><br></p>


In [27]:
from sklearn.svm import LinearSVC
SVM = LinearSVC(random_state=100, C=1.0)
SVM.fit(X_train, y_train)



C:\Users\hafsa\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=100, tol=0.0001,
     verbose=0)

In [28]:
predictions3=SVM.predict(X_test)
predictions3[:12]

array([27, 28, 14, 21,  6,  6, 14,  6, 24, 12,  6,  6], dtype=int64)

In [29]:
y_test['word'][:12]

59636    27
60866    28
29665    14
46825    21
18072     7
34393    16
28850    14
27842    13
53186    24
25632    12
47812    22
3311      1
Name: word, dtype: int64

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>
Le classificateur Naive Bayes 
<br><br></p>


In [30]:
from sklearn.naive_bayes import GaussianNB
gauss=GaussianNB()
gauss.fit(X_train,y_train)

C:\Users\hafsa\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None)

In [31]:
predictions4=gauss.predict(X_test)
predictions4[:20]

array([18, 28, 18,  5,  7, 16, 14, 14, 24, 12, 22,  1,  9, 17, 29,  6,  2,
        5,  5, 16], dtype=int64)

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>
Le classificateur K centroide
<br><br></p>


In [32]:
from sklearn.cluster import KMeans
kmeans=KMeans(n_clusters=2, random_state=100)
kmeans.fit(X_train,y_train)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=2, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=100, tol=0.0001, verbose=0)

In [33]:
predictions5=kmeans.predict(X_test)
predictions5[:10]

array([1, 1, 1, 0, 1, 1, 0, 0, 1, 0])

# RandomForestClassifier

In [51]:
from sklearn.ensemble import RandomForestClassifier

In [52]:
clf = RandomForestClassifier()

In [53]:
clf.fit(X_train,y_train)

C:\Users\hafsa\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [54]:
predictions6=clf.predict(X_test)

In [55]:
acc6=accuracy_score(y_true = y_test, y_pred = predictions6)

In [56]:
acc6

0.5061335331023504

# MLPClassifier

In [57]:
from sklearn.neural_network import MLPClassifier

In [58]:
clf2 = RandomForestClassifier()

In [63]:
clf2.fit(X_train,y_train)

C:\Users\hafsa\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [64]:
predictions7=clf2.predict(X_test)

In [65]:
acc7=accuracy_score(y_true = y_test, y_pred = predictions7)
print(acc7)

0.5049630115179324


# QuadraticDiscriminantAnalysis

In [62]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

In [66]:
clf3 = QuadraticDiscriminantAnalysis()
clf3.fit(X_train,y_train)
predictions8=clf3.predict(X_test)
acc8=accuracy_score(y_true = y_test, y_pred = predictions8)
print(acc8)

C:\Users\hafsa\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.7758217061522614


<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>

Mesurer l'accuracy, Mesurer f_mesure 
<br><br></p>


In [34]:
acc1=accuracy_score(y_true = y_test, y_pred = predictions1)
precision1=precision_score(y_test,predictions1,average=None)
recall1=recall_score(y_test,predictions1,average=None)
mesure1=f1_score(y_test,predictions1,average=None)

C:\Users\hafsa\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\hafsa\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [35]:
acc2=accuracy_score(y_true = y_test, y_pred = predictions2)
precision2=precision_score(y_test,predictions2,average=None)
recall2=recall_score(y_test,predictions2,average=None)
mesure2=f1_score(y_test,predictions2,average=None)

In [36]:
acc3=accuracy_score(y_true = y_test, y_pred = predictions3)
precision3=precision_score(y_test,predictions3,average=None)
recall3=recall_score(y_test,predictions3,average=None)
mesure3=f1_score(y_test,predictions3,average=None)

In [37]:
acc4=accuracy_score(y_true = y_test, y_pred = predictions4)
precision4=precision_score(y_test,predictions4,average=None)
recall4=recall_score(y_test,predictions4,average=None)
mesure4=f1_score(y_test,predictions4,average=None)

In [38]:
acc5=accuracy_score(y_true = y_test, y_pred = predictions5)
precision5=precision_score(y_test,predictions5,average=None)
recall5=recall_score(y_test,predictions5,average=None)
mesure5=f1_score(y_test,predictions5,average=None)

C:\Users\hafsa\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\hafsa\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [67]:
board=pd.DataFrame({
                    
                    "SVM":[format(acc3) ,format(recall3.mean()),format(precision3.mean()),format(mesure3.mean())],
                    "naive_bayes":[format(acc4) ,format(recall4.mean()),format(precision4.mean()),format(mesure4.mean())],
                    "AdaBoostClassifier":[format(acc_) ,format(recall_.mean()),format(precision_.mean()),format(mesure_.mean())],
                    "ExtraTreesClassifier":[format(acc) ,format(recall.mean()),format(precision.mean()),format(mesure.mean())],
                     "QuadraticDiscriminantAnalysis":[format(acc8) ]
        
                   }, 
                   index=['accuracy','moyenne rappell', 'moyenne precision','moyenne f_mesure']
)
board

AdaBoostClassifier ExtraTreesClassifier  \
accuracy            0.4050472890720105  0.45364734525704653   
moyenne rappell    0.40587557649713296  0.45692297921969355   
moyenne precision  0.40807627621489406   0.4700739034379739   
moyenne f_mesure    0.4017081560144267   0.4574717621015544   

                  QuadraticDiscriminantAnalysis                 SVM  \
accuracy                     0.7758217061522614  0.5225208352842027   
moyenne rappell              0.7758217061522614  0.5277252338133065   
moyenne precision            0.7758217061522614  0.8567160691486361   
moyenne f_mesure             0.7758217061522614  0.5974674041720374   

                          naive_bayes  
accuracy           0.5464462964697069  
moyenne rappell    0.5529280157528891  
moyenne precision  0.5825932580376717  
moyenne f_mesure   0.5562331171691276